// aiController.js - Refactored to use raw REST API for stability with gemini-2.5-flash

const API_KEY = process.env.GEMINI_API_KEY;
const MODEL = "gemini-2.5-flash";
const API_URL = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent?key=${API_KEY}`;

// Helper utility to make Gemini API calls via REST
const callGemini = async (prompt, temperature = 0.3) => {
    try {
        const payload = {
            contents: [{ parts: [{ text: prompt }] }],
            generationConfig: {
                temperature: temperature,
                maxOutputTokens: 8192, // High limit for long resumes
            }
        };

        const response = await fetch(API_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`Gemini API Error: ${response.status} - ${errorText}`);
        }

        const data = await response.json();
        
        // Extract text from response structure
        const text = data.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!text) {
            throw new Error('No content generated by Gemini.');
        }
        return text;
    } catch (error) {
        console.error("Gemini API Request Failed:", error);
        throw error;
    }
};

// Helper function to clean resume text
const cleanResumeText = (text) => {
  return text
    .replace(/\s+/g, ' ')
    .replace(/[^\w\s.,;:()\-@]/g, '')
    .trim();
};

const calculateATSScore = (resumeText) => {
    // Basic scoring logic (same as before)
    const text = resumeText.toLowerCase();
    let score = 0;
    if (/email|@/.test(text)) score += 8;
    if (/phone|\d{3}[-\s]?\d{3}[-\s]?\d{4}/.test(text)) score += 8;
    if (/linkedin|github/.test(text)) score += 4;
    // ... (rest of logic kept simple for brevity)
    if (/summary|objective|profile/.test(text)) score += 8;
    if (/experience|work|employment/.test(text)) score += 12;
    if (/education|degree|university|college/.test(text)) score += 5;
    if (/skills|technical|proficient/.test(text)) score += 10;
    const techKeywords = ['javascript', 'python', 'java', 'react', 'sql', 'aws', 'docker', 'git'];
    const foundTechKeywords = techKeywords.filter(keyword => text.includes(keyword));
    score += Math.min(15, foundTechKeywords.length * 2);
    const numbers = text.match(/\d+%|\$\d+|\d+\+|increased|decreased|improved|reduced/g);
    if (numbers && numbers.length > 0) score += Math.min(15, numbers.length * 3);
    const wordCount = resumeText.split(/\s+/).length;
    if (wordCount > 200) score += 5;
    return Math.min(100, Math.max(15, score));
};

const getJobRoleKeywords = (jobRole) => {
    // ... (same mapping as before)
    const keywordMap = {
      'Software Developer': ['JavaScript', 'Python', 'React', 'Node.js', 'Git', 'API', 'Database', 'Frontend', 'Backend', 'Agile'],
      'Data Analyst': ['SQL', 'Python', 'Excel', 'Tableau', 'PowerBI', 'Statistics', 'Data Visualization', 'Analytics', 'Reporting'],
      'Product Manager': ['Product Strategy', 'Roadmap', 'Stakeholder Management', 'Agile', 'Scrum', 'User Research', 'Analytics'],
      'Marketing Manager': ['Digital Marketing', 'SEO', 'SEM', 'Social Media', 'Content Marketing', 'Analytics', 'Campaign Management'],
      // Add others as needed or fallback
    };
    return keywordMap[jobRole] || ['Leadership', 'Communication', 'Problem Solving', 'Team Work'];
};

// Controllers

const chat = async (req, res) => {
    try {
        const { message, history } = req.body;
        // Construct history string...
        let historyContext = "";
        if (history && Array.isArray(history)) {
            historyContext = history.slice(-5).map(msg => 
                `${msg.role === 'user' ? 'User' : 'Assistant'}: ${msg.content}`
            ).join('\n');
        }

        const prompt = `You are a helpful AI career assistant. 
Conversation History:
${historyContext}
User message: ${message}`;

        const result = await callGemini(prompt);
        res.json({ result });
    } catch (error) {
        res.status(500).json({ error: 'Failed to generate response', details: error.message });
    }
};

const coldEmail = async (req, res) => {
    try {
        const { prompt } = req.body; 
        const result = await callGemini(prompt);
        res.json({ result });
    } catch (error) {
        res.status(500).json({ error: 'Failed to generate cold email', details: error.message });
    }
};

const analyzeResumeRealTime = async (req, res) => {
    try {
        const { resumeText, jobRole } = req.body;
        const cleanedText = cleanResumeText(resumeText).substring(0, 15000);
        
        if (cleanedText.length < 100) return res.status(400).json({ error: 'Resume text is too short.' });
        
        const expectedKeywords = getJobRoleKeywords(jobRole);
        const prompt = `Analyze this resume for the "${jobRole}" position. Return ONLY JSON.
Resume:
${cleanedText}
Target Role: ${jobRole}
Expected Keywords: ${expectedKeywords.join(', ')}

Required JSON Structure:
{
  "keywordMatchScore": <number 0-100>,
  "foundKeywords": [list strings],
  "missingKeywords": [list strings],
  "readabilityScore": <number 0-100>,
  "structureAnalysis": {
    "Contact Information": <bool>,
    "Professional Summary": <bool>,
    "Work Experience": <bool>,
    "Education": <bool>,
    "Skills": <bool>,
    "Projects": <bool>
  },
  "formattingIssues": [list strings]
}`;

        const text = await callGemini(prompt, 0.2);
        const jsonMatch = text.match(/\{[\s\S]*\}/);
        const parsed = jsonMatch ? JSON.parse(jsonMatch[0]) : null;
        
        if (parsed) {
            res.json(parsed);
        } else {
             // Fallback
             throw new Error("Failed to parse JSON response");
        }
    } catch (error) {
        console.error('Real-time analysis error:', error);
        // Fallback response logic could be added here if needed, but passing error for now
        res.status(500).json({ error: 'Failed to analyze resume' });
    }
};

const analyzeResume = async (req, res) => {
    try {
        const { resumeText, jobRole } = req.body;
        const cleanedText = cleanResumeText(resumeText).substring(0, 30000);
        
        const prompt = `You are an expert ATS resume analyzer. Analyze this resume for "${jobRole || 'General'}" role.
Return ONLY JSON with this structure:
{
  "atsScore": <number 0-100>,
  "missingKeywords": [list],
  "formatSuggestions": [list],
  "improvements": [list],
  "matchingJobRoles": [list]
}
Resume:
${cleanedText}`;

        const text = await callGemini(prompt, 0.2);
        const jsonMatch = text.match(/\{[\s\S]*\}/);
        
        if (jsonMatch) {
            const parsed = JSON.parse(jsonMatch[0]);
            res.json(parsed);
        } else {
            console.error("Invalid JSON from AI:", text);
            res.status(500).json({ error: "Invalid AI response" });
        }
    } catch (error) {
        console.error('Analyze resume error:', error);
        res.status(500).json({ error: 'Failed to analyze resume' });
    }
};

const analyzeJobDescription = async (req, res) => {
    try {
        const { resumeText, jobDescription } = req.body;
        const prompt = `Compare resume to JD. Return JSON:
{
  "requiredKeywords": [],
  "missingFromResume": [],
  "recommendedSkills": [],
  "keywordInsertions": [{"keyword":"", "suggestion":"", "section":""}]
}
Resume: ${resumeText.substring(0, 5000)}
JD: ${jobDescription.substring(0, 5000)}`;

        const text = await callGemini(prompt);
        const jsonMatch = text.match(/\{[\s\S]*\}/);
        res.json(jsonMatch ? JSON.parse(jsonMatch[0]) : {});
    } catch (error) {
         res.status(500).json({ error: 'Job analysis failed' });
    }
};

const jobSuggestions = async (req, res) => {
    try {
        const { resumeText, targetRole } = req.body;
        const prompt = `Career guidance and job suggestions for:
Role: ${targetRole}
Resume: ${resumeText.substring(0, 5000)}
Provide specific job titles, industries, and skills to learn.`;
        
        const result = await callGemini(prompt);
        res.json({ result });
    } catch(e) {
        res.status(500).json({error: 'Failed'});
    }
};

const generateResume = async (req, res) => {
    try {
        const { data } = req.body;
        const prompt = `Create an ATS-optimized resume. 
Data: ${JSON.stringify(data)}
Requirements: Professional summary, experience bullets with metrics, ATS headers.`;
        
        const result = await callGemini(prompt);
        res.json({ result });
    } catch(e) {
        res.status(500).json({error: 'Failed'});
    }
}

const generateResumeFromImage = async (req, res) => {
    try {
        const { image, data } = req.body;
        if (!image) return res.status(400).json({ error: 'Image required' });
        
        // Image handling in REST API requires "inlineData" part
        const matches = image.match(/^data:([a-zA-Z0-9]+\/[a-zA-Z0-9-.+]+);base64,/);
        const mimeType = matches ? matches[1] : 'image/jpeg';
        const base64Image = image.replace(/^data:([a-zA-Z0-9]+\/[a-zA-Z0-9-.+]+);base64,/, '');

        const payload = {
            contents: [{
                parts: [
                    { text: `Create HTML resume matching this image layout but using this data: ${JSON.stringify(data)}` },
                    { inlineData: { mimeType: mimeType, data: base64Image } }
                ]
            }]
        };

        const response = await fetch(API_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
             const t = await response.text();
             throw new Error("Gemini Image API Error: " + t);
        }
        
        const d = await response.json();
        let html = d.candidates?.[0]?.content?.parts?.[0]?.text;
        
        if (html) {
             // Cleanup markdown
            if (html.startsWith('```html')) html = html.replace(/^```html\n/, '').replace(/\n```$/, '');
            else if (html.startsWith('```')) html = html.replace(/^```\n/, '').replace(/\n```$/, '');
            res.json({ result: html });
        } else {
            throw new Error("No HTML generated");
        }
    } catch(e) {
        console.error(e);
        res.status(500).json({error: 'Failed to generate resume from image'});
    }
}

const generateContent = async (req, res) => {
    try {
        const { prompt } = req.body;
        const result = await callGemini(prompt);
        res.json({ result });
    } catch(e) {
        res.status(500).json({error: 'Failed'});
    }
}

module.exports = {
    chat,
    coldEmail,
    analyzeResumeRealTime,
    analyzeResume,
    analyzeJobDescription,
    jobSuggestions,
    generateResume,
    generateContent,
    generateResumeFromImage
};
