const User = require('../models/User');

const API_KEY = process.env.OPENROUTER_API_KEY;
const MODEL = "openai/gpt-5.2";
const API_URL = "https://openrouter.ai/api/v1/chat/completions";
const OPENROUTER_REFERER = process.env.OPENROUTER_REFERER || process.env.CLIENT_URL || 'http://localhost:5173';

const AI_LIMIT = 5;

// Helper to check and increment AI usage
const checkAndIncrementUsage = async (userId) => {
    const user = await User.findById(userId);
    if (!user) throw new Error('User not found');
    
    // Whitelist the owner's email for unlimited usage
    const whitelist = ['anuragsinghj678@gmail.com'];
    if (whitelist.includes(user.email)) {
        return user.aiUsage;
    }
    
    if (user.aiUsage >= AI_LIMIT) {
        throw new Error(`AI usage limit reached (${AI_LIMIT} attempts). Please upgrade for more access.`);
    }
    
    user.aiUsage += 1;
    await user.save();
    return user.aiUsage;
};

// Helper utility to make OpenRouter API calls
const callAI = async (prompt, temperature = 0.3, maxTokens = 1500) => {
    try {
        const response = await fetch(API_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${API_KEY}`,
                'HTTP-Referer': OPENROUTER_REFERER,
                'X-OpenRouter-Title': 'Hire-X',
                'Content-Type': 'application/json',
            },
            body: JSON.stringify({
                model: MODEL,
                messages: [
                    {
                        role: 'user',
                        content: prompt,
                    },
                ],
                temperature: temperature,
                max_tokens: maxTokens,
            }),
        });

        if (!response.ok) {
            const errorText = await response.text();
            throw new Error(`OpenRouter API Error: ${response.status} - ${errorText}`);
        }

        const data = await response.json();
        
        // Extract text from OpenRouter/OpenAI response structure
        const text = data.choices?.[0]?.message?.content;
        if (!text) {
            throw new Error('No content generated by AI.');
        }
        return text;
    } catch (error) {
        console.error("AI API Request Failed:", error);
        throw error;
    }
};

// Helper function to clean resume text
const cleanResumeText = (text) => {
  return text
    .replace(/\s+/g, ' ')
    .replace(/[^\w\s.,;:()\-@]/g, '')
    .trim();
};

const calculateATSScore = (resumeText) => {
    // Basic scoring logic (same as before)
    const text = resumeText.toLowerCase();
    let score = 0;
    if (/email|@/.test(text)) score += 8;
    if (/phone|\d{3}[-\s]?\d{3}[-\s]?\d{4}/.test(text)) score += 8;
    if (/linkedin|github/.test(text)) score += 4;
    // ... (rest of logic kept simple for brevity)
    if (/summary|objective|profile/.test(text)) score += 8;
    if (/experience|work|employment/.test(text)) score += 12;
    if (/education|degree|university|college/.test(text)) score += 5;
    if (/skills|technical|proficient/.test(text)) score += 10;
    const techKeywords = ['javascript', 'python', 'java', 'react', 'sql', 'aws', 'docker', 'git'];
    const foundTechKeywords = techKeywords.filter(keyword => text.includes(keyword));
    score += Math.min(15, foundTechKeywords.length * 2);
    const numbers = text.match(/\d+%|\$\d+|\d+\+|increased|decreased|improved|reduced/g);
    if (numbers && numbers.length > 0) score += Math.min(15, numbers.length * 3);
    const wordCount = resumeText.split(/\s+/).length;
    if (wordCount > 200) score += 5;
    return Math.min(100, Math.max(15, score));
};

const getJobRoleKeywords = (jobRole) => {
    // ... (same mapping as before)
    const keywordMap = {
      'Software Developer': ['JavaScript', 'Python', 'React', 'Node.js', 'Git', 'API', 'Database', 'Frontend', 'Backend', 'Agile'],
      'Data Analyst': ['SQL', 'Python', 'Excel', 'Tableau', 'PowerBI', 'Statistics', 'Data Visualization', 'Analytics', 'Reporting'],
      'Product Manager': ['Product Strategy', 'Roadmap', 'Stakeholder Management', 'Agile', 'Scrum', 'User Research', 'Analytics'],
      'Marketing Manager': ['Digital Marketing', 'SEO', 'SEM', 'Social Media', 'Content Marketing', 'Analytics', 'Campaign Management'],
      // Add others as needed or fallback
    };
    return keywordMap[jobRole] || ['Leadership', 'Communication', 'Problem Solving', 'Team Work'];
};

// Controllers

const chat = async (req, res) => {
    try {
        await checkAndIncrementUsage(req.user._id);
        const { message, history } = req.body;
        // Construct history string...
        let historyContext = "";
        if (history && Array.isArray(history)) {
            historyContext = history.slice(-5).map(msg => 
                `${msg.role === 'user' ? 'User' : 'Assistant'}: ${msg.content}`
            ).join('\n');
        }

        const prompt = `You are a helpful AI career assistant. 
Conversation History:
${historyContext}
User message: ${message}`;

        const result = await callAI(prompt);
        res.json({ result });
    } catch (error) {
        res.status(error.message.includes('limit reached') ? 403 : 500).json({ error: error.message || 'Failed to generate response' });
    }
};

const coldEmail = async (req, res) => {
    try {
        await checkAndIncrementUsage(req.user._id);
        const { prompt } = req.body; 
        const result = await callAI(prompt);
        res.json({ result });
    } catch (error) {
        res.status(error.message.includes('limit reached') ? 403 : 500).json({ error: error.message || 'Failed to generate cold email' });
    }
};

const analyzeResumeRealTime = async (req, res) => {
    try {
        await checkAndIncrementUsage(req.user._id);
        const { resumeText, jobRole } = req.body;
        const cleanedText = cleanResumeText(resumeText).substring(0, 15000);
        
        if (cleanedText.length < 100) return res.status(400).json({ error: 'Resume text is too short.' });
        
        const expectedKeywords = getJobRoleKeywords(jobRole);
        const prompt = `Analyze this resume for the "${jobRole}" position. Return ONLY JSON.
Resume:
${cleanedText}
Target Role: ${jobRole}
Expected Keywords: ${expectedKeywords.join(', ')}

Required JSON Structure:
{
  "keywordMatchScore": <number 0-100>,
  "foundKeywords": [list strings],
  "missingKeywords": [list strings],
  "readabilityScore": <number 0-100>,
  "structureAnalysis": {
    "Contact Information": <bool>,
    "Professional Summary": <bool>,
    "Work Experience": <bool>,
    "Education": <bool>,
    "Skills": <bool>,
    "Projects": <bool>
  },
  "formattingIssues": [list strings]
}`;

        const text = await callAI(prompt, 0.2);
        const jsonMatch = text.match(/\{[\s\S]*\}/);
        const parsed = jsonMatch ? JSON.parse(jsonMatch[0]) : null;
        
        if (parsed) {
            res.json(parsed);
        } else {
             // Fallback
             throw new Error("Failed to parse JSON response");
        }
    } catch (error) {
        console.error('Real-time analysis error:', error);
        res.status(error.message.includes('limit reached') ? 403 : 500).json({ error: error.message || 'Failed to analyze resume' });
    }
};

const analyzeResume = async (req, res) => {
    try {
        await checkAndIncrementUsage(req.user._id);
        const { resumeText, jobRole } = req.body;
        const cleanedText = cleanResumeText(resumeText).substring(0, 30000);
        
        const prompt = `You are an expert ATS resume analyzer. Analyze this resume for "${jobRole || 'General'}" role.
Return ONLY JSON with this structure:
{
  "atsScore": <number 0-100>,
  "missingKeywords": [list],
  "formatSuggestions": [list],
  "improvements": [list],
  "matchingJobRoles": [list]
}
Resume:
${cleanedText}`;

        const text = await callAI(prompt, 0.2);
        const jsonMatch = text.match(/\{[\s\S]*\}/);
        
        if (jsonMatch) {
            const parsed = JSON.parse(jsonMatch[0]);
            res.json(parsed);
        } else {
            console.error("Invalid JSON from AI:", text);
            res.status(500).json({ error: "Invalid AI response" });
        }
    } catch (error) {
        console.error('Analyze resume error:', error);
        res.status(error.message.includes('limit reached') ? 403 : 500).json({ error: error.message || 'Failed to analyze resume' });
    }
};

const analyzeJobDescription = async (req, res) => {
    try {
        await checkAndIncrementUsage(req.user._id);
        const { resumeText, jobDescription } = req.body;
        const prompt = `Compare resume to JD. Return JSON:
{
  "requiredKeywords": [],
  "missingFromResume": [],
  "recommendedSkills": [],
  "keywordInsertions": [{"keyword":"", "suggestion":"", "section":""}]
}
Resume: ${resumeText.substring(0, 5000)}
JD: ${jobDescription.substring(0, 5000)}`;

        const text = await callAI(prompt);
        const jsonMatch = text.match(/\{[\s\S]*\}/);
        res.json(jsonMatch ? JSON.parse(jsonMatch[0]) : {});
    } catch (error) {
         res.status(error.message.includes('limit reached') ? 403 : 500).json({ error: error.message || 'Job analysis failed' });
    }
};

const jobSuggestions = async (req, res) => {
    try {
        await checkAndIncrementUsage(req.user._id);
        const { resumeText, targetRole } = req.body;
        const prompt = `Career guidance and job suggestions for:
Role: ${targetRole}
Resume: ${resumeText.substring(0, 5000)}
Provide specific job titles, industries, and skills to learn.`;
        
        const result = await callAI(prompt);
        res.json({ result });
    } catch(error) {
        res.status(error.message.includes('limit reached') ? 403 : 500).json({ error: error.message || 'Failed' });
    }
};

const generateResume = async (req, res) => {
    try {
        await checkAndIncrementUsage(req.user._id);
        const { data } = req.body;
        const prompt = `Create an ATS-optimized resume. 
Data: ${JSON.stringify(data)}
Requirements: Professional summary, experience bullets with metrics, ATS headers.`;
        
        const result = await callAI(prompt);
        res.json({ result });
    } catch(error) {
        res.status(error.message.includes('limit reached') ? 403 : 500).json({ error: error.message || 'Failed' });
    }
}

const generateContent = async (req, res) => {
    try {
        await checkAndIncrementUsage(req.user._id);
        const { prompt } = req.body;
        const result = await callAI(prompt);
        res.json({ result });
    } catch(error) {
        res.status(error.message.includes('limit reached') ? 403 : 500).json({ error: error.message || 'Failed' });
    }
}

module.exports = {
    chat,
    coldEmail,
    analyzeResumeRealTime,
    analyzeResume,
    analyzeJobDescription,
    jobSuggestions,
    generateResume,
    generateContent,
};
